// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyslzrnmnqzntmuwzkwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5c2x6cm5tbnF6bnRtdXd6a3duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NDY0NzAsImV4cCI6MjA3MTUyMjQ3MH0.0PtAkO3XRr43iqh3Atqs_GigIUeH1zDz8rk2KpYqb7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});